import { formatOklch } from './color';
import type { ColorScheme } from './scheme';
import type { ResolvedScheme } from './scheme';

export function schemeToJson(scheme: ColorScheme): string {
  return JSON.stringify(scheme, null, 2);
}

export function schemeFromJson(json: string): ColorScheme {
  // Unvalidated cast — caller must supply well-formed JSON matching ColorScheme shape.
  return JSON.parse(json) as ColorScheme;
}

export function generateCss(resolved: ResolvedScheme, scheme: ColorScheme): string {
  const lines: string[] = [];
  lines.push(`/* Generated by color-schemer — scheme: ${scheme.name} */`);
  lines.push('');

  // Palette as custom properties on pre code.hljs
  lines.push('pre code.hljs,');
  lines.push('code.hljs {');
  for (const c of scheme.palette.colors) {
    lines.push(`  --${c.name}: ${formatOklch(c.color)};`);
  }
  lines.push('');
  lines.push(`  --cs-font: ${formatOklch(resolved.base.font)};`);
  lines.push(`  --cs-back: ${formatOklch(resolved.base.back)};`);
  lines.push('}');
  lines.push('');

  // Base rule
  lines.push('pre code.hljs {');
  lines.push('  display: block;');
  lines.push('  overflow-x: auto;');
  lines.push('  padding: 1em;');
  lines.push(`  color: ${formatOklch(resolved.base.font)};`);
  lines.push(`  background: ${formatOklch(resolved.base.back)};`);
  lines.push('}');
  lines.push('');

  // Entry rules
  for (const entry of resolved.entries) {
    if (entry.classes.length === 0) continue;
    if (entry.font === null && entry.back === null) continue;
    lines.push(entry.classes.join(',\n') + ' {');
    if (entry.font !== null) lines.push(`  color: ${formatOklch(entry.font)};`);
    if (entry.back !== null) lines.push(`  background-color: ${formatOklch(entry.back)};`);
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

/** Generate CSS suitable for injection into a <style> tag for live preview. */
export function generateLiveCss(resolved: ResolvedScheme): string {
  const lines: string[] = [];
  lines.push(
    `pre code.hljs { color: ${formatOklch(resolved.base.font)}; background: ${formatOklch(resolved.base.back)}; }`
  );
  for (const entry of resolved.entries) {
    if (entry.classes.length === 0) continue;
    const props: string[] = [];
    if (entry.font !== null) props.push(`color: ${formatOklch(entry.font)}`);
    if (entry.back !== null) props.push(`background-color: ${formatOklch(entry.back)}`);
    if (props.length > 0) lines.push(`${entry.classes.join(', ')} { ${props.join('; ')}; }`);
  }
  return lines.join('\n');
}
