import { formatOklch } from './color';
import type { ColorScheme } from './scheme';
import type { ResolvedScheme } from './scheme';

export function schemeToJson(scheme: ColorScheme): string {
  return JSON.stringify(scheme, null, 2);
}

export function schemeFromJson(json: string): ColorScheme {
  // Unvalidated cast — caller must supply well-formed JSON matching ColorScheme shape.
  return JSON.parse(json) as ColorScheme;
}

/** Convert an hljs scope name to its CSS selector.
 *  "comment"               → ".hljs-comment"
 *  "title.class"           → ".hljs-title.class_"
 *  "title.class.inherited" → ".hljs-title.class_.inherited__"
 *  "meta keyword"          → ".hljs-meta .hljs-keyword"
 */
export function scopeToCssSelector(scope: string, prefix = '.hljs-'): string {
  if (scope.includes(' ')) {
    return scope.split(' ').map((s) => prefix + s).join(' ');
  }
  if (scope.includes('.')) {
    const parts = scope.split('.');
    const sub = parts.slice(1).map((s, i) => s + '_'.repeat(i + 1)).join('.');
    return prefix + parts[0] + '.' + sub;
  }
  return prefix + scope;
}

export function generateCss(resolved: ResolvedScheme, scheme: ColorScheme): string {
  const lines: string[] = [];
  lines.push(`/* Generated by color-schemer — scheme: ${scheme.name} */`);
  lines.push('');

  // Palette as custom properties on pre code.hljs
  lines.push('pre code.hljs,');
  lines.push('code.hljs {');
  for (const c of scheme.palette.colors) {
    lines.push(`  --${c.name}: ${formatOklch(c.color)};`);
  }
  lines.push('');
  if (resolved.base.font) lines.push(`  --cs-font: ${formatOklch(resolved.base.font)};`);
  if (resolved.base.back) lines.push(`  --cs-back: ${formatOklch(resolved.base.back)};`);
  lines.push('}');
  lines.push('');

  // Base rule
  lines.push('pre code.hljs {');
  lines.push('  display: block;');
  lines.push('  overflow-x: auto;');
  lines.push('  padding: 1em;');
  if (resolved.base.font) lines.push(`  color: ${formatOklch(resolved.base.font)};`);
  if (resolved.base.back) lines.push(`  background: ${formatOklch(resolved.base.back)};`);
  lines.push('}');
  lines.push('');

  // Entry rules
  for (const entry of resolved.entries) {
    if (entry.classes.length === 0) continue;
    if (entry.font === null && entry.back === null) continue;
    lines.push(entry.classes.map((c) => scopeToCssSelector(c)).join(',\n') + ' {');
    if (entry.font !== null) lines.push(`  color: ${formatOklch(entry.font)};`);
    if (entry.back !== null) lines.push(`  background-color: ${formatOklch(entry.back)};`);
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

/** Generate CSS suitable for injection into a <style> tag for live preview. */
export function generateLiveCss(resolved: ResolvedScheme): string {
  const lines: string[] = [];
  const baseProps: string[] = [];
  if (resolved.base.font) baseProps.push(`color: ${formatOklch(resolved.base.font)}`);
  if (resolved.base.back) baseProps.push(`background: ${formatOklch(resolved.base.back)}`);
  if (baseProps.length) lines.push(`pre code.hljs { ${baseProps.join('; ')}; }`);
  for (const entry of resolved.entries) {
    if (entry.classes.length === 0) continue;
    const props: string[] = [];
    if (entry.font !== null) props.push(`color: ${formatOklch(entry.font)}`);
    if (entry.back !== null) props.push(`background-color: ${formatOklch(entry.back)}`);
    if (props.length > 0) lines.push(`${entry.classes.map((c) => scopeToCssSelector(c)).join(', ')} { ${props.join('; ')}; }`);
  }
  return lines.join('\n');
}
