/** Canonical list of highlight.js semantic scope names. */
export const HLJS_CLASSES: readonly string[] = [
  'comment',
  'quote',
  'doctag',
  'keyword',
  'type',
  'template-tag',
  'name',
  'selector-tag',
  'variable',
  'template-variable',
  'tag',
  'subst',
  'attr',
  'attribute',
  'built_in',
  'punctuation',
  'operator',
  'bullet',
  'string',
  'number',
  'literal',
  'regexp',
  'link',
  'symbol',
  'variable.constant',
  'selector-id',
  'selector-class',
  'title',
  'title.class',
  'title.class.inherited',
  'title.function',
  'section',
  'meta',
  'meta keyword',
  'meta string',
  'meta-keyword',
  'deletion',
  'addition',
  'strong',
  'emphasis',
] as const;
