/** Canonical list of highlight.js semantic classes derived from the reference CSS. */
export const HLJS_CLASSES: readonly string[] = [
  '.hljs-comment',
  '.hljs-quote',
  '.hljs-doctag',
  '.hljs-keyword',
  '.hljs-type',
  '.hljs-template-tag',
  '.hljs-name',
  '.hljs-selector-tag',
  '.hljs-variable',
  '.hljs-template-variable',
  '.hljs-tag',
  '.hljs-subst',
  '.hljs-attr',
  '.hljs-attribute',
  '.hljs-built_in',
  '.hljs-punctuation',
  '.hljs-operator',
  '.hljs-bullet',
  '.hljs-string',
  '.hljs-number',
  '.hljs-literal',
  '.hljs-regexp',
  '.hljs-link',
  '.hljs-symbol',
  '.hljs-variable.constant_',
  '.hljs-selector-id',
  '.hljs-selector-class',
  '.hljs-title',
  '.hljs-title.class_',
  '.hljs-title.class_.inherited__',
  '.hljs-title.function_',
  '.hljs-function .hljs-title',
  '.hljs-section',
  '.hljs-meta',
  '.hljs-meta .hljs-keyword',
  '.hljs-meta .hljs-string',
  '.hljs-meta-keyword',
  '.hljs-deletion',
  '.hljs-addition',
  '.hljs-strong',
  '.hljs-emphasis',
] as const;
